<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>10.2 custom errors</title>
</head>
<body>
<script>


    class MyError extends Error {
        constructor(message) {
            super(message);
            this.name = this.constructor.name;
        }
    }

    class ValidationError extends MyError {
        constructor(message) {
            super(message); // (1)
            this.name = "ValidationError"; // (2)
        }
    }

    class PropertyRequiredError extends ValidationError {
        constructor(property) {
            super("Нет свойства: " + property);
            this.name = "PropertyRequiredError";
            this.property = property;
        }
    }

    class ReadError extends Error {
        constructor(message, cause) {
            super(message);
            this.cause = cause;
            this.name = 'ReadError';
        }
    }

    function test() {
        throw new ValidationError("Упс!");
    }

    try {
        test();
    } catch(err) {
        console.log(err.message); // Упс!
        console.log(err.name); // ValidationError
        console.log(err.stack); // список вложенных вызовов с номерами строк для каждого
    }


    // Использование
    // Применение
    function readUser(json) {
        let user = JSON.parse(json);

        if (!user.age) {
            throw new PropertyRequiredError("age");
        }
        if (!user.name) {
            throw new PropertyRequiredError("name");
        }

        return user;
    }

    // Рабочий пример с try..catch

    try {
        let user = readUser('{ "age": 25 }');
    } catch (err) {
        if (err instanceof ValidationError) {
            alert("Неверные данные: " + err.message); // Неверные данные: Нет свойства: name
            alert(err.name); // PropertyRequiredError
            alert(err.property); // name
        } else if (err instanceof SyntaxError) {
            alert("Ошибка синтаксиса JSON: " + err.message);
        } else {
            throw err; // неизвестная ошибка, повторно выбросит исключение
        }
    }





    function validateUser(user) {
        if (!user.age) {
            throw new PropertyRequiredError("age");
        }

        if (!user.name) {
            throw new PropertyRequiredError("name");
        }
    }

    function readUser(json) {
        let user;

        try {
            user = JSON.parse(json);
        } catch (err) {
            if (err instanceof SyntaxError) {
                throw new ReadError("Синтаксическая ошибка", err);
            } else {
                throw err;
            }
        }

        try {
            validateUser(user);
        } catch (err) {
            if (err instanceof ValidationError) {
                throw new ReadError("Ошибка валидации", err);
            } else {
                throw err;
            }
        }

    }

    try {
        readUser('{bad json}');
    } catch (e) {
        if (e instanceof ReadError) {
            alert(e);
            // Исходная ошибка: SyntaxError:Unexpected token b in JSON at position 1
            alert("Исходная ошибка: " + e.cause);
        } else {
            throw e;
        }
    }
</script>
</body>
</html>